version: '3'
services:
  selenium-hub:
    image: selenium/hub
    ports:
      - "4444:4444"
    networks:
      - selenium-network

  chrome:
    image: selenium/node-chrome
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    ports:
      - "5900:5900"
    networks:
      - selenium-network

networks:
  selenium-network:
    driver: bridge

